[package]
name = "rs_library"
version = "0.1.0"
authors = ["toyama1710 <walker2002226@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
